win: fix cuda build
Current build fails with
  error C2398: Element '1': conversion from 'cute::C<128>' to 'unsigned int' requires a narrowing conversion